export { useAlumnoStore } from '~~/stores/alumnos'
export { useAsignaturaStore } from '~~/stores/asignaturas'
export { useMatriculaStore } from '~~/stores/matriculas'
export { useEvaluationStore } from '~~/stores/evaluation'
export { useEvaluationItemStore } from '~~/stores/evaluationItems'
export { useRubricaStore } from '~~/stores/rubricas'
export { useRubricaGroupStore } from '~~/stores/rubricaGroups'
export { useEquivalenceStore } from '~~/stores/equivalences'